export let content = document.createElement("div");
content.setAttribute("id", "cotent");

let card1 = document.createElement("div");
card1.setAttribute("class", "card");
card1.setAttribute("id", "tiitle");
card1.textContent = "Contact Us";
content.appendChild(card1);

let card2 = document.createElement("div");
card2.setAttribute("class", "card");
let card2heading = document.createElement("div");
card2heading.setAttribute("class", "cardHeading");
card2heading.textContent = "Sanji";
card2.append(card2heading);
// let card2text= document.createElement("div");
// card2text.setAttribute("class","cardtext");
let item1 = document.createElement("div");
item1.setAttribute("class", "cardtext");
item1.textContent = "Head Chef";
card2.append(item1);
let item2 = document.createElement("div");
item2.setAttribute("class", "cardtext");
item2.textContent = "Head Chef";
card2.append(item2);
let item3 = document.createElement("div");
item3.setAttribute("class", "cardtext");
item3.textContent = "Head Chef";
card2.append(item3);
content.appendChild(card2);
// card2.append(card2text);
